### ISSUE TITLE
rauth uses wrong request URI, causes missing consumer key error (?)

### ISSUE THREAD

**Issue by trtg** [litl/rauth#14]
I'm trying to access the fatsecret API. I've successfully accessed this same API with the python-fatsecret library from here https://bitbucket.org/fmoo/python-fatsecret   I'm using the exact same consumer key with rauth as I did with python-fatsecret but rauth is giving me the following error in get_request_token: (I added some print statements in service.py)
"response <Response [400]>
response.content  Missing required parameter: oauth_consumer_key"

but I'm definitely instantiating OAuth1Service with a consumer key(and I've triple checked that it is correct).
I ran wireshark while getting a request token using rauth and python-fatsecret and noticed these differences:

rauth: OAuth Realm="http://www.fatsecret.com/"  and request_URI=/oauth_request_token

python-fatsecret: OAuth Realm="" and request_URI = http://www.fatsecret.com/oauth/request_token?oauth_nonce=77769080&oauth_timestamp=1339285156&oauth_consumer_key=my_key_was_here&oauth_signature_method=HMAC-SHA1&oauth_version=1.0&oauth_signature=8a3mb2veTNIPkW6kNWr8J2pyxQ4%3D&oauth_callback=oob

Any hints on why rauth is doing a GET on the wrong URI(or am I misunderstanding what's going on)? I just pulled from the repo today, so I'm using rauth 0.4.6.

**Comment by ChocoTonic** [comment]
hi all,

this is a super old thread, but I was trying to get this script by @jrnold to work:
[https://github.com/jrnold/fatsecretExporter/blob/master/fatsecretExport.py](https://github.com/jrnold/fatsecretExporter/blob/master/fatsecretExport.py)

and inside, it refers to this link mentioned earlier:
[https://bitbucket.org/fmoo/python-fatsecret](https://bitbucket.org/fmoo/python-fatsecret)

but I get a 404
![image](https://user-images.githubusercontent.com/41702116/64563037-32abe700-d303-11e9-8e12-fa7c39ba0ff2.png)

I'm running python 2.7 and installed oauth and ConfigureParser using pip, but when it gets to FatSecretClient, it doesn't work, and I think that has to do FatSecretClient being missing and hosting issues. 

```
Traceback (most recent call last):
  File "C:\Users\[Redacted]\Desktop\FatSecretExporter\FatSecretExporter.py", line 9, in <module>
    from fatsecret import FatSecretClient, TokenShelf
ImportError: cannot import name FatSecretClient
```

Do any of you have backups of whatever was on [https://bitbucket.org/fmoo/python-fatsecret](https://bitbucket.org/fmoo/python-fatsecret) or @fmoo's contact information so I could ask him about his repo?

@tristan @jobi @tko @sethdill @bbigras
