### ISSUE TITLE
car2go API unsupported

### ISSUE THREAD

**Issue by mhenry** [litl/rauth#178]
I'm trying to connect to the [car2go API via OAuth 1.0/a](https://code.google.com/p/car2go/wiki/oauth) and I'm getting an `oauth_problem="signature_invalid"`. Below is the code I'm using to connect:

```
from rauth import OAuth1Service
 
car2go = OAuth1Service(
    name='car2go',
    consumer_key='REDACTED',
    consumer_secret='REDACTED',
    request_token_url='https://www.car2go.com/api/reqtoken',
    authorize_url='https://www.car2go.com/api/authorize',
    access_token_url='https://www.car2go.com/api/accesstoken',
    base_url='http://www.car2go.com/api/v2.1/')
 
request_token, request_token_secret = car2go.get_request_token(params={'oauth_callback': 'oob'})
```

The `oauth_callback` param is required for this API and I'm wondering it causes any problems with the calculation of the signature.

**Comment by maxcountryman** [comment]
`oauth_callback` is used as part of the signature when provided.

**Comment by mhenry** [comment]
I was given incorrect API credentials. This is not an issue with `rauth`.
