### ISSUE TITLE
Using rauth for twitter Oauth1 get_raw_access_token and get_auth_session

### ISSUE THREAD

**Issue by jmgamboa** [litl/rauth#187]
Hey guys. Really great module. its a shame twitter cannot move to oauth2. Anyway, I'm
using rauth for twitters Oauth1Service client.  I keep getting a 401 on get_raw_access_token and when i try using get_auth_session and OAuth request: Invalid oauth_verifier parameter. i followed the docs as mentioned and do not seem to be doing out of the ordinary. I even tried explicitly passing the request method as 'GET'

```
    twitter = OAuth1Service(
            consumer_key='somethingconsumerkey',
            consumer_secret='somethingsecret',
            name='twitter',
            access_token_url='https://api.twitter.com/oauth/access_token',
            authorize_url='https://api.twitter.com/oauth/authorize',
            request_token_url='https://api.twitter.com/oauth/request_token',
            base_url='https://api.twitter.com/1/')
    request_token, request_token_secret = twitter.get_request_token()
    authorize_url = twitter.get_authorize_url(request_token)
    twitter.get_access_token(request_token, request_token_secret, method='GET')
     # or 
    twitter.get_raw_access_token(request_token, request_token_secret)
    # or 
    twitter.get_auth_session(request_token, request_token_secret)
```

**Comment by maxcountryman** [comment]
Hi,

Could you post the tulle traceback?

Thanks!

**Comment by jmgamboa** [comment]
KeyError: 'Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: Error processing your OAuth request: Invalid oauth_verifier parameter' must i explicitly pass a decoder function?

**Comment by maxcountryman** [comment]
If the Twitter response cannot be automatically parsed, then yes.

**Comment by jmgamboa** [comment]
do you believe this is the issue? https://github.com/litl/rauth/issues/145. states you would still get the request object back. if the response is not decoded. also get_raw_access_token yields a 401 which is unauthorized

**Comment by maxcountryman** [comment]
Based on the error you pasted, you need a custom decoder.

**Comment by jmgamboa** [comment]
what kind of decoder? i see in the documentation <function parse_utf8_qsl>. and does this explain the 401 as well?

**Comment by maxcountryman** [comment]
I think your call to `get_auth_session` needs to provide an `oauth_verifier`. See the [Twitter example](https://github.com/litl/rauth/blob/master/examples/twitter-timeline-cli.py#L25-L28).

**Comment by jmgamboa** [comment]
I really need to mention that I appreciate your responses. Thank you. However, I meant an example for decoders. @maxcountryman i get the 401 error with get_raw_access_token() anyway to see the traceback? also i'm using hellojs with rauth as a backend if that provides any insight.

**Comment by maxcountryman** [comment]
Can you try to execute the example?

**Comment by jmgamboa** [comment]
its late and going to bed but will try tomorrow. the only issue is that i dont like the pin implementation

**Comment by maxcountryman** [comment]
I'm not suggesting you use it for your application, but I would like you to try it so we can determine where your problem is. I ran the example earlier without problem. It's functionally the same up until it requests an auth token.

**Comment by jmgamboa** [comment]
the example works and am able to get the access token and token secret from get_auth_session. but i did notice that theres a redirect after authorizing the app redirects me to a different intended domain. i just want localhost. this might be the issue. i will work it throughout the day and get back to you
