### ISSUE TITLE
Ability to overwrite the callback_url on Oauth1Service 

### ISSUE THREAD

**Issue by jmgamboa** [litl/rauth#189]
Callback_url is specified in your apps.twitter.com console. does rauth provide the ability to over ride this callback and specify your own?

**Comment by maxcountryman** [comment]
This behavior is defined by the provider (Twitter) so you'll have to dig into their documentation to find out.

**Comment by jmgamboa** [comment]
so get_request_token can take a param called oauth_callback in the params option. 
an example of this looks like 
service.get_request_token(params={'oauth_callback':'http://www.overriddencallbackurl.com'})

**Comment by maxcountryman** [comment]
That's right--you can pass arbitrary parameters to the token request. But it's important to note that the provider defines where this value you can be defined. For instance, Facebook requires that this value be defined ahead of time via their developer console.

**Comment by jmgamboa** [comment]
Facebook allows you to define multiple callback urls whereas the twitter console only allows one to be defined in their settings so over riding the predefined one was important for me. Thanks for the replies, and good work on the package.
