### ISSUE TITLE
Twitter Authentication Failing on Python 3.6

### ISSUE THREAD

**Issue by TwoBitAlchemist** [litl/rauth#195]
The following works on Python 3.5

    service = OAuth1Service(
        name='twitter',
        consumer_key=os.environ['TWITTER_APP_KEY'],
        consumer_secret=os.environ['TWITTER_APP_SECRET'],
        request_token_url='https://api.twitter.com/oauth/request_token',
        authorize_url='https://api.twitter.com/oauth/authorize',
        access_token_url='https://api.twitter.com/oauth/access_token',
        base_url='https://api.twitter.com/1.1/'
    )

    request_token = service.get_request_token(params={'oauth_callback': callback_url})
    service.get_authorize_url(request_token[0])

    # in callback
    oauth_session = service.get_auth_session(
        request_token[0], request_token[1],
        data={'oauth_verifier': oauth_verifier}
    )

On Python 3.6 I get:

      File "/project/app/auth/providers.py", line 77, in callback
    data={'oauth_verifier': oauth_verifier}
      File "/project/lib/python3.6/site-packages/rauth/service.py", line 359, in get_auth_session
    **kwargs)
      File "/project/lib/python3.6/site-packages/rauth/service.py", line 332, in get_access_token
    process_token_request(r, decoder, key_token, key_token_secret)
      File "/project/lib/python3.6/site-packages/rauth/service.py", line 24, in process_token_request
    raise KeyError(PROCESS_TOKEN_ERROR.format(key=bad_key, raw=r.content))
    KeyError: "Decoder failed to handle oauth_token_secret with data as returned by provider. A different decoder may be needed. Provider returned: b'oauth_token=[some_auth_token]&oauth_token_secret=[some_secret]&user_id=[number]&screen_name=[name]&x_auth_expires=0'"

Both using rauth 0.7.2

**Comment by TwoBitAlchemist** [comment]
The problem is [here](https://github.com/litl/rauth/blob/master/rauth/utils.py#L30). You are changing a dictionary as you are iterating over it. The dict type has been [reimplemented in Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-compactdict) to be more memory efficient, following an enhancement by the PyPy team. So something about this internal change has caused the `oauth_token_secret` key to get skipped by `parse_utf8_qsl` (it is not converted and is still bytes at the end). The solution should be to produce a new dict instead of trying to modify the one in place.

Edited to Add: I opened a [PR](https://github.com/litl/rauth/pull/196) with a working fix. Only a very small change was needed.

**Comment by maxcountryman** [comment]
Nice catch @TwoBitAlchemist! 👍

**Comment by TwoBitAlchemist** [comment]
Glad I could help actually find the bug instead of only being able to complain :)

Closing this issue since it's fixed in [0.7.3](https://pypi.python.org/pypi/rauth/0.7.3)

**Comment by souaaz** [comment]
Thanks!
