### ISSUE TITLE
OAuth 1.0 requests issues

### ISSUE THREAD

**Issue by nyov** [litl/rauth#66]
I'm having some issues in 0.5 with OAuth 1.0

The default oauth_callback got dropped?
Ok, I got that working again by adding `params={'oauth_callback': 'oob'}` into `service.get_request_token()` for my specific API.

Some more trouble was `session.request()` when trying to set a content-type header:
Unless it's named exactly `'Content-Type'` (e.g. application/json) the request will add it instead of replacing the default `'Content-Type': 'application/x-www-form-urlencoded'`, which is strange because it should be case insensitive.

The real problem I can't figure out though is, that a `session.post()` even with setting `header_auth=True` will silently eat any `data=payload` if it's json encoded:
`r = session.post(url,data=json.dumps({'status':'ok'})`
will have an empty `r.request.data`.

And on another note, I was missing some error reporting if the server response is something other than 200 in the authentication stage.
I had to hack some 'print's into the source to catch server responses like `oauth_problem=parameter_absent&oauth_parameters_absent=oauth_verifier` or `oauth_problem=parameter_rejected&message=oauth_callback` which only failed with "obscure" lines like

``` python
  File "[...]/rauth.git/rauth/service.py", line 191, in get_request_token
    return data['oauth_token'], data['oauth_token_secret']
KeyError: 'oauth_token'
```

**Comment by Padmahas** [comment]
Hello @maxcountryman ,
I'm trying to implement OAuth1 for JIRA and I'm still getting the same error here.
```
Traceback (most recent call last):
  File "/media/padmahasa/84a76bf2-5545-4b02-a6a7-d4cfc51c0a9b/python_progs/venv/lib/python3.8/site-packages/rauth/service.py", line 21, in process_token_request
    return tuple(data[key] for key in args)
  File "/media/padmahasa/84a76bf2-5545-4b02-a6a7-d4cfc51c0a9b/python_progs/venv/lib/python3.8/site-packages/rauth/service.py", line 21, in <genexpr>
    return tuple(data[key] for key in args)
KeyError: 'oauth_token'
```
Does that mean, JIRA haven't return a key named, 'oauth_token'?
And as you have suggested earlier, I tried to use
`print(jira.get_raw_request_token())`
But all Output I'm getting is,
`<Response [200]>`
Can you please help me on how to print the whole response as is?

Also there is one followup error saying.
```
During handling of the above exception, another exception occurred:
File "/media/padmahasa/84a76bf2-5545-4b02-a6a7-d4cfc51c0a9b/python_progs/venv/lib/python3.8/site-packages/rauth/service.py", line 24, in process_token_request
    raise KeyError(PROCESS_TOKEN_ERROR.format(key=bad_key, raw=r.content))
KeyError: "Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: b''"
```
As you can see, there is only Empty string inside "Provider returned" message.
I'm bit clueless here.

Thank you.
